CREATE TABLE dev_login_slot (
    slot_number INT NOT NULL PRIMARY KEY,
    user_id BIGINT NULL UNIQUE,
    session_id VARCHAR(36) NULL UNIQUE,
    token_id VARCHAR(36) NULL UNIQUE,
    expires_at DATETIME(6) NULL,
    CONSTRAINT fk_dev_login_user FOREIGN KEY (user_id) REFERENCES user(user_id)
);

INSERT INTO dev_login_slot (slot_number)
SELECT tens.n * 10 + ones.n + 1
FROM (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens
CROSS JOIN (SELECT 0 n UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4
      UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones;
