spring:
  application:
    name: server

  config:
    import: optional:file:.env[.yml]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
  #    properties:
  #      hibernate:
  #        show_sql: true
  #        format_sql: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_REST_API_KEY}
            client-secret: 1aad561b8ca76979450e2a05adaf8b35
            scope: profile_nickname,account_email
            client-name: kakao-login
            authorization-grant-type: authorization_code
            redirect-uri: ${SERVER_URL}/oauth2/callback/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

app:
  auth:
    tokenSecret: ${JWT_SECRET_KEY}
    tokenExpirationMsec: 86400000
    refreshTokenExpirationMsec: 1209600000
  oauth2:
    authorizedRedirectUris:
      - https://waps.im/oauth2/redirect
      - https://wapst.netlify.app/oauth2/redirect
      - https://waps-deploy.netlify.app/oauth2/redirect
      - https://waps-web.netlify.app/oauth2/redirect
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

swagger:
  server-url: ${SWAGGER_SERVER_URL}

project:
  password: 1248

#logging:
#  level:
#    org.springframework.security: DEBUG

## monitoring
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, prometheus, metrics
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
    metrics:
      enabled: true
