name: Code Review
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  issue_comment:
    types:
      - created

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  setup-deepseek-review:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    name: Code Review
    steps:
      - name: DeepSeek Code Review
        uses: psvm203/deepseek-review@v1.0
        with:
          model: "deepseek-v4-flash"
          watch-mention: "/review"
          chat-token: ${{ secrets.DEEPSEEK_API_KEY }}
          sys-prompt: "당신은 전문 코드 리뷰어입니다. 풀 리퀘스트에서 변경 사항을 파악하고 코드와 같은 잠재적인 문제를 식별하세요. 스타일 위반, 논리적 오류, 보안 취약을 찾아내고 개선사항을 제공하세요. 문제점과 권고사항, 제안을 간결하게 명확히 나열하세요. 한국어로 답변하세요."
